USE [BDAMPLUS]
SELECT TOP 5 P.[ID_CODPRODUTO] as id, P.[PROD_DESCABREVIADA] as name, P.[PROD_CODBARRA] as barcode, PD.[PRDE_RUA] as street, PD.[PRDE_FILEIRA] as shelf
FROM [PRODUTOS] P
LEFT JOIN [PRODUTODEPOSITO] PD ON P.[ID_CODPRODUTO] = PD.[ID_CODPRODUTO]
WHERE PD.[ID_CODFILIAIS] = 1
AND PD.[ID_DEPOSITOS] = 2
AND P.[PROD_CODBARRA] = @barcode